name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # 사용할 JDK 배포판
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'

            echo "Deploying as user: ${{ secrets.EC2_USER }}"
            cd /home/${{ secrets.EC2_USER }}
                            
            if [ -d "my-spring-board" ]; then
              cd my-spring-board
              git pull
            else
              git clone https://github.com/captain-yun/my-spring-board.git
              cd my-spring-board
            fi          
            chmod +x ./gradlew
            ./gradlew clean build -x test
            pm2 delete my-spring-board || true
            pm2 start java -jar ./build/libs/my-spring-board2-0.0.1-SNAPSHOT.jar
          EOF
